"""
=========================================================
SRSentinel AI
PDF Report Generator
=========================================================
"""

import os

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle
)
from reportlab.lib.units import inch


class ReportGenerator:

    def __init__(self):

        self.styles = getSampleStyleSheet()

        self.title_style = ParagraphStyle(
            "TitleStyle",
            parent=self.styles["Heading1"],
            alignment=TA_CENTER,
            textColor=colors.darkblue,
            fontSize=22,
            spaceAfter=20
        )

        self.heading_style = ParagraphStyle(
            "HeadingStyle",
            parent=self.styles["Heading2"],
            textColor=colors.darkblue,
            spaceBefore=15,
            spaceAfter=10
        )

        self.normal_style = self.styles["BodyText"]

    # --------------------------------------------------
    # Generate PDF Report
    # --------------------------------------------------

    def generate_report(
        self,
        original_text,
        prediction,
        classification,
        ambiguity,
        quality,
        xai,
        suggestions
    ):

        output_path = "SRSentinel_AI_Report.pdf"

        document = SimpleDocTemplate(
            output_path,
            rightMargin=30,
            leftMargin=30,
            topMargin=30,
            bottomMargin=30
        )

        elements = []

        # ------------------------------------------------
        # Cover Page
        # ------------------------------------------------

        elements.append(
            Paragraph(
                "SRSentinel AI",
                self.title_style
            )
        )

        elements.append(
            Paragraph(
                "Software Requirement Specification Quality Analysis Report",
                self.styles["Heading2"]
            )
        )

        elements.append(Spacer(1, 0.3 * inch))

        elements.append(
            Paragraph(
                "<b>Generated By:</b> SRSentinel AI",
                self.normal_style
            )
        )

        elements.append(
            Paragraph(
                "<b>Technology:</b> NLP + Machine Learning + Explainable AI",
                self.normal_style
            )
        )

        elements.append(Spacer(1, 0.25 * inch))
        # ------------------------------------------------
        # Prediction Summary
        # ------------------------------------------------

        elements.append(
            Paragraph(
                "Prediction Summary",
                self.heading_style
            )
        )

        prediction_data = [

            ["Prediction", prediction["quality"]],

            ["Confidence", f'{prediction["confidence"]}%'],

            ["Confidence Level", prediction["confidence_level"]],

            ["Quality Score", f'{quality["quality_score"]}/100'],

            ["Percentage", f'{quality["percentage"]}%'],

            ["Grade", quality["grade"]],

            ["Status", quality["status"]]

        ]

        prediction_table = Table(
            prediction_data,
            colWidths=[220, 220]
        )

        prediction_table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (0, -1), colors.lightgrey),

                ("GRID", (0, 0), (-1, -1), 1, colors.black),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),

                ("FONTNAME", (0, 0), (-1, -1), "Helvetica")

            ])

        )

        elements.append(prediction_table)

        elements.append(Spacer(1, 0.25 * inch))

        # ------------------------------------------------
        # Requirement Statistics
        # ------------------------------------------------

        elements.append(

            Paragraph(

                "Requirement Statistics",

                self.heading_style

            )

        )

        stats = classification["statistics"]

        statistics_table = Table(

            [

                ["Metric", "Count"],

                ["Total Requirements", stats["total"]],

                ["Functional Requirements", stats["functional"]],

                ["Non Functional Requirements", stats["non_functional"]],

                ["Other Requirements", stats["others"]]

            ],

            colWidths=[250, 180]

        )

        statistics_table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.black),

                ("BACKGROUND", (0, 1), (0, -1), colors.beige),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8)

            ])

        )

        elements.append(statistics_table)

        elements.append(Spacer(1, 0.25 * inch))

        # ------------------------------------------------
        # Ambiguity Analysis
        # ------------------------------------------------

        elements.append(

            Paragraph(

                "Ambiguity Analysis",

                self.heading_style

            )

        )

        ambiguity_table = Table(

            [

                ["Metric", "Value"],

                ["Ambiguous Words", ambiguity["count"]],

                ["Severity", ambiguity["severity"]],

                ["Ambiguity Score", ambiguity["ambiguity_score"]]

            ],

            colWidths=[250, 180]

        )

        ambiguity_table.setStyle(

            TableStyle([

                ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),

                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),

                ("GRID", (0, 0), (-1, -1), 1, colors.black),

                ("BACKGROUND", (0, 1), (0, -1), colors.beige),

                ("BOTTOMPADDING", (0, 0), (-1, -1), 8)

            ])

        )

        elements.append(ambiguity_table)

        elements.append(Spacer(1, 0.30 * inch))
                # ------------------------------------------------
        # Explainable AI Analysis
        # ------------------------------------------------

        elements.append(
            Paragraph(
                "Explainable AI Analysis",
                self.heading_style
            )
        )

        elements.append(
            Paragraph(
                "<b>Positive Indicators</b>",
                self.normal_style
            )
        )

        for item in xai["positive_indicators"]:

            elements.append(
                Paragraph(
                    "• " + item,
                    self.normal_style
                )
            )

        elements.append(
            Spacer(1, 0.10 * inch)
        )

        elements.append(
            Paragraph(
                "<b>Negative Indicators</b>",
                self.normal_style
            )
        )

        for item in xai["negative_indicators"]:

            elements.append(
                Paragraph(
                    "• " + item,
                    self.normal_style
                )
            )

        elements.append(
            Spacer(1, 0.20 * inch)
        )

        # ------------------------------------------------
        # AI Explanation
        # ------------------------------------------------

        elements.append(
            Paragraph(
                "AI Explanation",
                self.heading_style
            )
        )

        elements.append(
            Paragraph(
                xai["explanation"],
                self.normal_style
            )
        )

        elements.append(
            Spacer(1, 0.25 * inch)
        )

        # ------------------------------------------------
        # Feature Importance
        # ------------------------------------------------

        elements.append(
            Paragraph(
                "Feature Importance",
                self.heading_style
            )
        )

        feature_data = [["Feature", "Value"]]

        for key, value in xai["feature_importance"].items():

            feature_data.append([key, str(value)])

        feature_table = Table(
            feature_data,
            colWidths=[250, 180]
        )

        feature_table.setStyle(
            TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), colors.darkblue),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("GRID", (0, 0), (-1, -1), 1, colors.black),
                ("BACKGROUND", (0, 1), (0, -1), colors.beige),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8)
            ])
        )

        elements.append(feature_table)

        elements.append(
            Spacer(1, 0.30 * inch)
        )
                # ------------------------------------------------
        # Improvement Suggestions
        # ------------------------------------------------

        elements.append(
            Paragraph(
                "Improvement Suggestions",
                self.heading_style
            )
        )

        for suggestion in suggestions.get(
            "ambiguity_suggestions", []
        ):
            elements.append(
                Paragraph(
                    "• " + suggestion,
                    self.normal_style
                )
            )

        for suggestion in suggestions.get(
            "functional_suggestions", []
        ):
            elements.append(
                Paragraph(
                    "• " + suggestion,
                    self.normal_style
                )
            )

        for suggestion in suggestions.get(
            "non_functional_suggestions", []
        ):
            elements.append(
                Paragraph(
                    "• " + suggestion,
                    self.normal_style
                )
            )

        elements.append(
            Spacer(1, 0.20 * inch)
        )

        # ------------------------------------------------
        # Best Practices
        # ------------------------------------------------

        elements.append(
            Paragraph(
                "Best Practices",
                self.heading_style
            )
        )

        for item in suggestions.get(
            "best_practices", []
        ):
            elements.append(
                Paragraph(
                    "• " + item,
                    self.normal_style
                )
            )

        elements.append(
            Spacer(1, 0.25 * inch)
        )

        # ------------------------------------------------
        # Quality Improvement Checklist
        # ------------------------------------------------

        elements.append(
            Paragraph(
                "Quality Improvement Checklist",
                self.heading_style
            )
        )

        for item in suggestions.get(
            "improvement_checklist", []
        ):
            elements.append(
                Paragraph(
                    "✔ " + item,
                    self.normal_style
                )
            )

        elements.append(
            Spacer(1, 0.30 * inch)
        )

        # ------------------------------------------------
        # Extracted SRS Text
        # ------------------------------------------------

        elements.append(
            Paragraph(
                "Extracted SRS Document",
                self.heading_style
            )
        )

        elements.append(
            Paragraph(
                original_text.replace("\n", "<br/>"),
                self.normal_style
            )
        )

        elements.append(
            Spacer(1, 0.30 * inch)
        )
                # ------------------------------------------------
        # Footer
        # ------------------------------------------------

        elements.append(
            Spacer(1, 0.30 * inch)
        )

        elements.append(
            Paragraph(
                "<br/><br/>"
                "<b>SRSentinel AI</b><br/><br/>"
                "Generated using Artificial Intelligence,<br/>"
                "Natural Language Processing (NLP)<br/>"
                "and Machine Learning.<br/><br/>"
                "&copy; 2026 SRSentinel AI",
                self.styles["Italic"]
            )
        )

        # ------------------------------------------------
        # Build PDF
        # ------------------------------------------------

        document.build(elements)

        # ------------------------------------------------
        # Return PDF Bytes
        # ------------------------------------------------

        with open(output_path, "rb") as pdf_file:
            pdf_bytes = pdf_file.read()

        return pdf_bytes